"""Protocol constants."""

DEFAULT_PORT = 23
DEFAULT_RECONNECT_SECONDS = 5.0
DEFAULT_COMMAND_THROTTLE_SECONDS = 0.2

PROMPT_USER = "User:"
PROMPT_PASSWORD = "Password:"
PROMPT_CONNECTED = "Connected:"

PREFIX_COMMAND = "#"
PREFIX_EVENT = "!"
POSTFIX = ";"

MOTOR_ALL = "1.1.0.MOTOR"
MOTOR_A = "1.1.1.MOTOR"
MOTOR_B = "1.1.2.MOTOR"
MOTOR_C = "1.1.3.MOTOR"
MOTOR_D = "1.1.4.MOTOR"

COMMAND_UP = "UP"
COMMAND_DOWN = "DOWN"
COMMAND_STOP = "STOP"
COMMAND_RETRACT = "RETRACT"
COMMAND_RECALL = "RECALL"
COMMAND_STORE = "STORE"

QUERY_POSITION = "POSITION"

EVENT_STATUS = "STATUS"
EVENT_POSITION = "POSITION"

STATUS_STOP = "STOP"
STATUS_RETRACTING = "RETRACTING"
STATUS_EXTENDING = "EXTENDING"
STATUS_HOME = "HOME"
STATUS_END = "END"
